README.md
package.json

* [MOB-4023](https://iterable.atlassian.net/browse/MOB-4023)
Updates docs to include imports on example usage sections
1. None - just read the README :)

Updates Documentation

---

package.json
yarn.lock

N/A
Upgrades version and removes unused handlebars dependency
1. N/A

Upgrade Version

---

README.md
package.json

* [MOB-4097](https://iterable.atlassian.net/browse/MOB-4097)
Updates README to include information about how clicking links works
[View file here](https://github.com/Iterable/iterable-web-sdk/blob/325065592960fdf76ba63382fb8a8734f3d00e94/README.md)

Update README with Link Clicking Docs

---

README.md

* [MOB-4098](https://iterable.atlassian.net/browse/MOB-4098)
Updates README to explain how JWTs are regenerated
Read the [updated README here](https://github.com/Iterable/iterable-web-sdk/blob/0d02c2e93476324ddf84985b0afbdc76a9c6c8fa/README.md)

Update README to Include JWT Regeneration Methods

---

.github/workflows/publish.yml

* [MOB-4113](https://iterable.atlassian.net/browse/MOB-4113)
Update publish pipeline to run on release published instead of release created, so we can create draft releases and then mark them as published
N/A - can't test this one

Update Publish CI Run Condition

---

package.json

0.1.2 Version Bump

---

src/authorization/authorization.ts

* [MOB-4262](https://iterable.atlassian.net/browse/MOB-4262)
Fixes issue where calling `setEmail` or `setUserID` a second time would not reset the timeout for regenerating a JWT and instead regenerate the JWT with the email/userID you passed the first time you identified a user.
1. Run a local JWT generation backend by [cloning this repo](https://github.com/Iterable/jwt-generator) and running `docker-compose up -d`
2. Run react example app in this repo with `yarn install:all && yarn start:all:react`
3. Open up `localhost:8080` in your browser and use the login form in the header to login with an email
4. Change logged-in user by clicking the login button again and submit a different email
5. Wait ~1 minute for the `/generate` endpoint to be called again and ensure the newly signed in …

Reset Auth Timer With New User

---

package.json

Update to 0.1.3

---

package.json

Upgrade to Version 0.2.0

---

example/package.json
example/yarn.lock
package.json
react-example/package.json
react-example/yarn.lock
src/inapp/tests/inapp.test.ts
yarn.lock

* [MOB-4238](https://iterable.atlassian.net/browse/MOB-4238)
Upgrades and syncs TypeScript versions across SDK and example apps and fixes new errors
1. Run `yarn install:all && yarn start:all:react` and ensure app still runs correctly
2. Run `yarn test` and ensure tests still pass correctly

Upgrades TypeScript and Fixes New Errors

---

package.json

Version bump to 0.2.1

---

package.json

v0.3.0 Release

---

yarn.lock

* [MOB-4726](https://iterable.atlassian.net/browse/MOB-4726)
Update webpack dependency to resolve terser vulnerability

[MOB-4726] Resolve security issues with dependency: terser

---

README.md

https://iterable.atlassian.net/browse/MOB-4737
Adding documentation

[MOB-4737] - Update README for getInAppMessages

---

example/index.html
example/src/styles/index.css
react-example/index.html
react-example/src/styles/index.css
src/inapp/inapp.ts

* [MOB-4789](https://iterable.atlassian.net/browse/MOB-4789)
Some small refactorings for inapp.ts in prep for public beta. No new functionality.
Removes giant footer from sample apps.
1. All unit tests pass.
2. No randomly huge footer with unprofessional "hi im the footer" text on the page.
3. `trackInAppOpen`, `trackInAppConsume`, and `trackInAppClose` work as expected

[MOB-4789] Refactor inapp.ts and remove excessive footers from sample apps

---

package.json

* [MOB-4798](https://iterable.atlassian.net/browse/MOB-4798)
Version upgrade
N/A

[MOB-4798] Upgrade version to v0.4.1

---

package.json

* [MOB-4853](https://iterable.atlassian.net/browse/MOB-4853)
Version upgrade
N/A

[MOB-4853] Upgrade version to v0.4.2

---

src/__data__/inAppMessages.ts
src/inapp/utils.ts

* [MOB-4936](https://iterable.atlassian.net/browse/MOB-4936)
Even though there isn't a scrollbar, the iframe height differs from the actual iframe document's html's height. The extra 10px of adjustment fixes issue for top/bottom/center layouts (not applicable in full layout).
Also refactors mock data to make it more usable with cache testing.
Paint inapp to screen in top/bottom/center layouts.
Place mouse over the message and scroll.
Message should not move.

[MOB-4936] Fix issue with discrepancy in iframe heights and refactor mock data to test cached messages

---

src/inapp/inapp.ts

* [MOB-4956](https://iterable.atlassian.net/browse/MOB-4956)
Moving logic not related to handleLinks outside of the manageHandleLinks method.
Also make update to handle _self target for links in Safari.
Test all link permutations (no target, target, no target with handleLinks, target with handleLinks) with Chrome, Firefox, and Safari

[MOB-4956] Refactor link handling

---

src/inapp/inapp.ts
src/inapp/tests/utils.test.ts
src/inapp/types.ts
src/inapp/utils.ts

* [MOB-5009](https://iterable.atlassian.net/browse/MOB-5009)
No need to wait until expiration to delete messages from cache.
Delete cached messages if they do not appear in the fetched messages response.

[MOB-5009] Delete cached messages that do not appear in getMessages request

---

package.json

* [MOB-4946](https://iterable.atlassian.net/browse/MOB-4946)

[MOB-4946] Update version to v1.0.0

---

src/authorization/authorization.ts

* [MOB-5653](https://iterable.atlassian.net/browse/MOB-5653)
Reduce timeout handling of JWT token to under 1 day.
[MOB-5653]: https://iterable.atlassian.net/browse/MOB-5653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Change timeout to 1 day

---

src/authorization/authorization.test.ts
src/authorization/authorization.ts
src/authorization/utils.test.ts
src/authorization/utils.ts

* [MOB-5654](https://iterable.atlassian.net/browse/MOB-5654)
[MOB-5654]: https://iterable.atlassian.net/browse/MOB-5654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-5654] JWT Token To Be Refreshed Manually

---

src/authorization/authorization.test.ts
src/authorization/authorization.ts
src/authorization/utils.ts

fix issue -infinite loop when expiration time in jwt is wrong

---

README.md

Docs updates for new `refreshJwtToken` method.

[MOB-5654] Docs updates for refreshJwtToken

---

package.json

* [MOB-6617](https://iterable.atlassian.net/browse/MOB-6617)
Bumps SDK version to account for new environment variables to make use of the new EUDC endpoints. 
[MOB-6617]: https://iterable.atlassian.net/browse/MOB-6617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6617]: EUDC Release Cut

---

src/embedded/IterableActionRunner.ts

Remove build fail error

---

src/embedded/embeddedManager.ts

Resolve merge conflicts

---

package.json

* [MOB-7555](https://iterable.atlassian.net/browse/MOB-7555)
[MOB-7555]: https://iterable.atlassian.net/browse/MOB-7555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7555]: Release 1.0.7

---

src/embedded/IterableActionRunner.ts

Resolve build fail issue

---

README.md

https://iterable.atlassian.net/browse/MOB-7682
Special link handling applies to all iOS browsers so we need to account for those and document

[MOB-7682] Updating iOS browser handling

---

react-example/src/views/EmbeddedMsgs.tsx
src/components/banner/index.tsx
src/components/card/index.tsx

* [MOB-7844](https://iterable.atlassian.net/browse/MOB-7844)
> Set responsive view for embedded Card/Banner/Notification view.
[MOB-7844]: https://iterable.atlassian.net/browse/MOB-7844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mob 7844 (Content for OOTB not responding properly)

---

src/components/notification/index.tsx

* [MOB-7845](https://iterable.atlassian.net/browse/MOB-7845)
> Margin has been removed to properly align the notification view.
[MOB-7845]: https://iterable.atlassian.net/browse/MOB-7845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mob 7845 (Content not aligned for notification view)

---

src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx

* [MOB-7846](https://iterable.atlassian.net/browse/MOB-7846)
> We have set the default text align for default button style.
[MOB-7846]: https://iterable.atlassian.net/browse/MOB-7846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mob 7846 (Buttons in card view not properly aligning with long text)

---

src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx

* [MOB-7842](https://iterable.atlassian.net/browse/MOB-7842)
> We have set cursor turn into pointer when hovering over the message for all view.
[MOB-7842]: https://iterable.atlassian.net/browse/MOB-7842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-7842 (turn cursor into pointer)

---

package.json

* [MOB-7921](https://iterable.atlassian.net/browse/MOB-7921)
[MOB-7921]: https://iterable.atlassian.net/browse/MOB-7921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7921] bump version to 1.0.8

---

react-example/package.json
react-example/yarn.lock

* [MOB-7841](https://iterable.atlassian.net/browse/MOB-7841)
> We have updated the relevant package to use a lower version of jest-worker@28.1.3.
[MOB-7841]: https://iterable.atlassian.net/browse/MOB-7841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mob 7841 (Lower `jest-worker@28.1.3` version in react-example)

---

react-example/src/views/Home.tsx
src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx

* [MOB-7982](https://iterable.atlassian.net/browse/MOB-7982)
> make OOTB views  unavailable for Beta release.
[MOB-7982]: https://iterable.atlassian.net/browse/MOB-7982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

make OOTB views  unavailable for Beta

---

src/embedded/embeddedManager.test.ts
src/embedded/embeddedManager.ts
src/embedded/types.ts

* [MOB-7972](https://iterable.atlassian.net/browse/MOB-7972)
> We've removed the action handlers as they are no longer needed.
[MOB-7972]: https://iterable.atlassian.net/browse/MOB-7972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mob 7972 (Embedded message action handlers)

---

react-example/src/views/Home.tsx
src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx

* [MOB-8056](https://iterable.atlassian.net/browse/MOB-8056)
Adding back exports
[MOB-8056]: https://iterable.atlassian.net/browse/MOB-8056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8056]: Export OOTB views for sample app

---

package.json
react-example/src/views/Home.tsx
src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx

add react-example to prettier format command and run

---

src/authorization/authorization.ts
src/embedded/embeddedManager.ts

api calls were not being intercepted and injected with the proper email or userId

Fix embedded events api calls

---

src/authorization/authorization.ts

fix embedded session track call

---

react-example/package.json
react-example/src/components/EmbeddedForm.tsx
react-example/yarn.lock

* [MOB-8078](https://iterable.atlassian.net/browse/MOB-8078)
> We have set the uuid as session ID.
[MOB-8078]: https://iterable.atlassian.net/browse/MOB-8078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add uuid as session ID

---

src/index.ts
src/utils/IterableActionRunner.ts
src/utils/IterableConfig.ts
webpack.dev.config.js

Fix Class Export

---

package.json

* [MOB-8100](https://iterable.atlassian.net/browse/MOB-8100)
[MOB-8100]: https://iterable.atlassian.net/browse/MOB-8100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8100] Web SDK beta release 1.1.0-beta

---

.github/workflows/ci.yml

make checks in parity with publish

---

react-example/src/components/EmbeddedForm.tsx
react-example/src/views/EmbeddedMsgs.tsx
src/embedded/embeddedManager.test.ts
src/embedded/embeddedManager.ts

HTTP call in retrieveEmbeddedMessages

---

package.json

* [MOB-8379](https://iterable.atlassian.net/browse/MOB-8379)
bump to v1.0.9
[MOB-8379]: https://iterable.atlassian.net/browse/MOB-8379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8379] bump to v1.0.9

---

.github/workflows/ci.yml
.github/workflows/publish.yml

* [MOB-8397](https://iterable.atlassian.net/browse/MOB-8397)
- update to use commit hash in github actions to address https://iterable.atlassian.net/browse/ISRR-517
- update GA dependencies to latest releases
[MOB-8397]: https://iterable.atlassian.net/browse/MOB-8397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8397] replace with commit hash and update to latest releases

---

src/authorization/authorization.ts

* [MOB-8430](https://iterable.atlassian.net/browse/MOB-8430)
[MOB-8430]: https://iterable.atlassian.net/browse/MOB-8430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8430]: add /messages to interceptor routes for userId

---

src/authorization/authorization.ts

* [MOB-8452](https://iterable.atlassian.net/browse/MOB-8452)
[MOB-8452]: https://iterable.atlassian.net/browse/MOB-8452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8452] fix lint

---

EXAMPLE_APP.md
example/src/index.ts

`EXAMPLE_APP.md` was reworded to be more clear in the steps required to get started.
There were several TS errors when running `yarn start:all` that have been addressed in this commit.

tech: Update EXAMPLE_APP & Typescript fixes

---

README.md

* [DOCS-4682](https://iterable.atlassian.net/browse/DOCS-4682)
* [MOB-8515](https://iterable.atlassian.net/browse/MOB-8515)
* https://github.com/Iterable/iterable-web-sdk/pull/380
Updating README to describe new environment variable: `DANGEROUSLY_ALLOW_JS_POPUP_EXECUTION`
[DOCS-4682]: https://iterable.atlassian.net/browse/DOCS-4682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-8515]: https://iterable.atlassian.net/browse/MOB-8515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-4682] Information about allow-popups-to-escape-sandbox

---

README.md
package.json

* [MOB-8657](https://iterable.atlassian.net/browse/MOB-8657)
[MOB-8657]: https://iterable.atlassian.net/browse/MOB-8657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8657]: bump version to 1.0.11

---

README.md

Updates readme to more accurately match API of `initializeWithConfig`.

`initializeWithConfig` README updates

---

react-example/src/views/EmbeddedMsgs.tsx
src/components/banner/index.tsx
src/components/card/index.tsx
src/components/notification/index.tsx
src/components/types.ts

* [MOB-8639](https://iterable.atlassian.net/browse/MOB-8639)
Adds `elements` object to OOTB type to consolidate params. 
[MOB-8639]: https://iterable.atlassian.net/browse/MOB-8639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8639]: add elements to OOTB type

---

react-example/src/index.tsx

* [MOB-8674](https://iterable.atlassian.net/browse/MOB-8674)
param got reverted at some point. this resolves an issue with testing UUID logins
[MOB-8674]: https://iterable.atlassian.net/browse/MOB-8674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8674]: Fix UUID Jwt Generator Issue

---

package.json

* [MOB-8852](https://iterable.atlassian.net/browse/MOB-8852)
[MOB-8852]: https://iterable.atlassian.net/browse/MOB-8852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8852]: Embedded Release

---

.github/workflows/ci.yml
package.json
src/components/banner/index.tsx
src/components/card/index.tsx

* [MOB-8854](https://iterable.atlassian.net/browse/MOB-8854)
Adds prepublish check to PRs
Fixes issue caught on prepublish
[MOB-8854]: https://iterable.atlassian.net/browse/MOB-8854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8854]: Prepublish checks and fixes

---

README.md

* [DOCS-4747](https://iterable.atlassian.net/browse/DOCS-4747)
[DOCS-4747]: https://iterable.atlassian.net/browse/DOCS-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-4748] Close button updates

---

package.json

* [MOB-9119](https://iterable.atlassian.net/browse/MOB-9119)
Bumps semver for release
[MOB-9119]: https://iterable.atlassian.net/browse/MOB-9119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9119]: bump release version to v1.1.1

---

react-example/src/views/AUTTesting.tsx
src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/criteriaCompletionChecker.test.ts

* [MOB-9150](https://iterable.atlassian.net/browse/MOB-9150)
[WEB] Bools need to be a string to be evaluated
Video attached to the ticket
[MOB-9150]: https://iterable.atlassian.net/browse/MOB-9150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed bools needs to be string

---

react-example/src/views/AUTTesting.tsx
src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/criteriaCompletionChecker.test.ts

* [MOB-9138](https://iterable.atlassian.net/browse/MOB-9138)
DoesNotEqual does not seem to work for string, double, long, boolean
[MOB-9138]: https://iterable.atlassian.net/browse/MOB-9138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-9138: Resolves DoesNotEqual criteria match issue

---

src/anonymousUserTracking/anonymousUserEventManager.ts

* [MOB-9305](https://iterable.atlassian.net/browse/MOB-9305)
Replayed events don't have proper createdAt timestamp
[MOB-9305]: https://iterable.atlassian.net/browse/MOB-9305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-9305: fixed events createdAt timeStamps

---

src/anonymousUserTracking/tests/combinationLogicCriteria.test.ts

* [MOB-9168](https://iterable.atlassian.net/browse/MOB-9168)
Write automated unit tests against Combination logic with Event Type
[MOB-9168]: https://iterable.atlassian.net/browse/MOB-9168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-9168: Automated unit tests against Combination logic with Event Type

---

src/anonymousUserTracking/anonymousUserEventManager.ts
src/constants.ts
src/utils/config.ts

* [MOB-8824](https://iterable.atlassian.net/browse/MOB-8824)
Event storage configuration for AUT
[MOB-8824]: https://iterable.atlassian.net/browse/MOB-8824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-8824: Added limitation to event storage

---

.eslintrc
react-example/package.json
react-example/server/generate.py
react-example/server/server.js
react-example/src/index.tsx
react-example/yarn.lock

* [MOB-9328](https://iterable.atlassian.net/browse/MOB-9328)
> I have implemented code to generate JWT token using JWT enabled API key and JWT secret key.
[MOB-9328]: https://iterable.atlassian.net/browse/MOB-9328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB 9328 - Verify AUT works with JWT

---

src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/criteriaCompletionChecker.test.ts

* [MOB-9149](https://iterable.atlassian.net/browse/MOB-9149)
> Resolved error for crete anon user if input data fields are incorrect.
[MOB-9149]: https://iterable.atlassian.net/browse/MOB-9149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB 9149 - Sample app object updates not formatted properly

---

react-example/src/views/AUTTesting.tsx
src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/nestedTesting.test.ts

* [MOB-9308](https://iterable.atlassian.net/browse/MOB-9308)
Support nested field types
[MOB-9308]: https://iterable.atlassian.net/browse/MOB-9308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-9308: supports nested field types

---

README.md

Change EUDC to EDC in the SDK README.
* [DOCS-4858](https://iterable.atlassian.net/browse/DOCS-4858)
[DOCS-4858]: https://iterable.atlassian.net/browse/DOCS-4858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-4858] Change "EUDC" to "EDC"

---

src/anonymousUserTracking/tests/userMergeScenarios.test.ts
src/authorization/authorization.ts
src/utils/config.ts

* [MOB-9578](https://iterable.atlassian.net/browse/MOB-9578)
AUT SDK SetUserId / SetEmail Changes
implements identity resolution
[MOB-9578]: https://iterable.atlassian.net/browse/MOB-9578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9578] implements identity resolution

---

src/anonymousUserTracking/tests/complexCriteria.test.ts
src/anonymousUserTracking/tests/constants.ts

* [MOB-9168](https://iterable.atlassian.net/browse/MOB-9168)
Automated unit tests against complex criteria
[MOB-9168]: https://iterable.atlassian.net/browse/MOB-9168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9168] Automated unit tests against complex criteria

---

react-example/src/indexWithoutJWT.tsx
src/anonymousUserTracking/anonymousUserEventManager.ts
src/authorization/authorization.ts
src/utils/config.ts

* [MOB-9955](https://iterable.atlassian.net/browse/MOB-9955)
Allows devs to override identity resolution when setUserID or setEmail is called. 
[MOB-9955]: https://iterable.atlassian.net/browse/MOB-9955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9955]: Allow IdentityResolution Overrides and Move onAnonUserCreated in Config

---

src/authorization/authorization.ts

* [MOB-9964](https://iterable.atlassian.net/browse/MOB-9964)
JWT was not being generated in time before syncEvents was being called. To fix this, I've moved syncEvents to be called 
- separately
- in the case of with JWT, after the jwt has been generated. 
[MOB-9964]: https://iterable.atlassian.net/browse/MOB-9964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9964]: Fix Replay With JWT

---

src/anonymousUserTracking/tests/userMergeScenarios.test.ts
src/authorization/authorization.ts

* [MOB-9954](https://iterable.atlassian.net/browse/MOB-9954)
[MOB-9954]: https://iterable.atlassian.net/browse/MOB-9954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9954]: fix userMergeScenario test

---

src/anonymousUserTracking/anonymousUserEventManager.ts
src/anonymousUserTracking/tests/anonymousUserEventManager.test.ts

* [MOB-10056](https://iterable.atlassian.net/browse/MOB-10056)
[MOB-10056]: https://iterable.atlassian.net/browse/MOB-10056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10056]: rename createKnownUser -> createAnonymousUser

---

src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/constants.ts
src/anonymousUserTracking/tests/nestedTesting.test.ts

* [MOB-9970](https://iterable.atlassian.net/browse/MOB-9970)
[Web SDK] Visitor did not match anonymous criteria as expected
[MOB-9970]: https://iterable.atlassian.net/browse/MOB-9970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9970] anonymous criteria should match for nested values

---

src/anonymousUserTracking/criteriaCompletionChecker.ts
src/anonymousUserTracking/tests/compareArrayDataTypes.test.ts
src/anonymousUserTracking/tests/constants.ts
src/anonymousUserTracking/tests/nestedTesting.test.ts

* [MOB-10064](https://iterable.atlassian.net/browse/MOB-10064)
[Web SDK] single primitive array bug
[MOB-10064]: https://iterable.atlassian.net/browse/MOB-10064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10064] single primitive array bug fix

---

src/authorization/authorization.ts

* [MOB-10124](https://iterable.atlassian.net/browse/MOB-10124)
Adds public method for clearing anon session data. 
[MOB-10124]: https://iterable.atlassian.net/browse/MOB-10124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10124]: add method to clear anon data

---

src/commerce/commerce.ts
src/constants.ts
src/events/events.ts
src/users/users.ts

* [MOB-10121](https://iterable.atlassian.net/browse/MOB-10121)
[MOB-10121]: https://iterable.atlassian.net/browse/MOB-10121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10121]: Update Rejection Message for AUA events

---

package.json

* [MOB-10135](https://iterable.atlassian.net/browse/MOB-10135)
[MOB-10135]: https://iterable.atlassian.net/browse/MOB-10135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10135]: update release version

---

package.json

* [MOB-10139](https://iterable.atlassian.net/browse/MOB-10139)
[MOB-10139]: https://iterable.atlassian.net/browse/MOB-10139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10139]: bump version for release

---

package.json

* [MOB-11439](https://iterable.atlassian.net/browse/MOB-11439)
[MOB-11439]: https://iterable.atlassian.net/browse/MOB-11439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-11439] Upgrade Web SDK version to v1.2.0

---

example/package.json
example/yarn.lock
package.json
react-example/package.json
react-example/yarn.lock
yarn.lock

* [MOB-11487](https://iterable.atlassian.net/browse/MOB-11487)
* Upgrades webpack dependency to 5.99.9
[MOB-11487]: https://iterable.atlassian.net/browse/MOB-11487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-11487] Upgrade webpack dependency

---

package.json

* [MOB-11575](https://iterable.atlassian.net/browse/MOB-11575)
[MOB-11575]: https://iterable.atlassian.net/browse/MOB-11575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-11575] Bump version to v2.0.0

---

README.md
src/authorization/index.ts
src/commerce/commerce.test.ts
src/embedded/embeddedManager.test.ts
src/embedded/index.ts
src/events/events.test.ts
src/events/index.ts
src/inapp/index.ts
src/inapp/tests/inapp.test.ts
src/inapp/tests/utils.test.ts
src/index.ts
src/testing/index.ts
src/users/users.test.ts

* [MOB-11879](https://iterable.atlassian.net/browse/MOB-11879)
- adds README updates for UUA
- some other updates to make sure README is up to date
- removes some unintended exports
[MOB-11879]: https://iterable.atlassian.net/browse/MOB-11879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-11879]: export and readme updates for UUA

---

example/package.json
example/yarn.lock
package.json
react-example/package.json
react-example/yarn.lock
yarn.lock

* [MOB-12129](https://iterable.atlassian.net/browse/MOB-12129)
Bump on-headers version to resolve security vulnerabilities.
[MOB-12129]: https://iterable.atlassian.net/browse/MOB-12129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-12129] Resolve on-headers dependency security vulnerability

---

example/package.json
example/yarn.lock
package.json
react-example/package.json
react-example/yarn.lock
yarn.lock

* [MOB-12120](https://iterable.atlassian.net/browse/MOB-12120)
Bump axios dependency version to resolve security vulnerabilities
[MOB-12120]: https://iterable.atlassian.net/browse/MOB-12120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-12120] Bump axios dependency version to resolve security vulnerabilities

---

.github/workflows/codeql.yml
.gitignore

* [SEC-3677](https://iterable.atlassian.net/browse/SEC-3677)
This will enable the CodeQL SCA workflow for this repo
[SEC-3677]: https://iterable.atlassian.net/browse/SEC-3677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CodeQL initial commit
