src/authorization/authorization.ts, src/authorization/utils.ts, src/events/events.ts, src/inapp/inapp.ts, src/inapp/tests/inapp.test.ts, src/request.ts
* [MOB-4071](https://iterable.atlassian.net/browse/MOB-4071)
Previously, when a user opened an in-app message and clicked on a link that was going to navigate them to a new URL in the same tab, the `/trackInAppClick` request would be called, but never finish because the page was being unmounted.
Now, we persist the request using the `fetch` API's `keepalive` flag. Essentially what it does is makes sure the request finishes even though the user navigated to a new page.
🚨  PLEASE NOTE: In the Devtools on your browser, the request will be labeled as "unknown" because the browser doesn't actual know if the request succeeded or failed, and neither do we. We just simply hope for the best 🚨 
1. Send yourself a (non-proof) in-app message with a link that will navigate you in the same tab
* e.g. …
=> Persist /trackInAppClick When Navigating Away

.eslintignore, .gitignore, react-example/cypress/fixtures/commerce/200.json, react-example/cypress/fixtures/commerce/400.json, react-example/cypress/fixtures/events/200.json, react-example/cypress/integration/commerce/commerce.spec.ts, react-example/cypress/support/index.js, react-example/src/index.tsx
N/A
Abstracts common things that every cypress test needs to a setup file.
Essentially does 2 things:
1. intercepts all `/generate` requests so that the request to get a JWT token just auto-resolves without hitting a server
2. intercepts all tracking calls. When we eventually test in-app messages with cypress, i want to prevent any tracking calls to a server actually being made and just stub the `/getInAppMessages` call with mock HTML.
1. Install deps and run react app with `yarn install:all && yarn start:all:react`
2. `cd ./react-example && yarn cypress`
3. In the cypress window, run all the test and make sure they all pass
=> Abstract Common Cypress Setup

.prettierignore, react-example/cypress/fixtures/events/400.json, react-example/cypress/integration/events/events.spec.ts, react-example/cypress/support/index.js, react-example/src/components/EventsForm.tsx, react-example/src/index.tsx, react-example/src/views/Events.tsx, react-example/src/views/Home.tsx, src/index.ts
* [MOB-3929](https://iterable.atlassian.net/browse/MOB-3929)
Add Cypress Suite for Events Endpoints. Creates a base component to handle the forms for each endpoint and renders the form in `Events.tsx` with all the different /events endpoints
1. Run `yarn install:all && yarn start:all:react` to start the app
2. `cd ./react-example && yarn cypress` to run the cypress test runner
3. Click start in the Cypress window and run the `events.spec.ts` suite
4. Ensure all tests pass
=> Add Cypress Suite for Events Endpoints

example/index.html, example/src/styles/index.css, react-example/src/components/Button.tsx, react-example/src/components/Link.tsx, src/inapp/tests/utils.test.ts, src/inapp/utils.ts
* [MOB-4153](https://iterable.atlassian.net/browse/MOB-4153)
Fixes issue with iframe running past the height of the DOM.
Also updates misc. example app styles
1. Create in-app message with a lot of content that will go past 100% of the screen
* to test this, I just created one with 4-5 stacked images ([example here](https://i.imgur.com/PqpLEiF.png))
2. Send to yourself and run example app with `yarn install:all && yarn start:all`
3. See image only take up `95vh` height max (`100%` for full screen messages) and not overflow past the viewport
4. Try with different position settings and screen sizes
* on mobile breakpoints, the max height should be `85vh` (`100%` for full screen messages)
=> Updates Styles

react-example/src/components/Button.tsx, react-example/src/components/EventsForm.tsx, react-example/src/components/Link.tsx, react-example/src/components/LoginForm.tsx, react-example/src/components/TextField.tsx, react-example/src/index.tsx, react-example/src/views/Commerce.tsx, react-example/src/views/Components.styled.ts, react-example/src/views/Events.tsx, react-example/src/views/Home.tsx
* [MOB-3930](https://iterable.atlassian.net/browse/MOB-3930)
Adds login form to example app as a precursor the to the users endpoints form, so we can start manipulating the logged in user
1. Run a local JWT generation backend by [cloning this repo](https://github.com/Iterable/jwt-generator) and running `docker-compose up -d`
2. Run react example app in this repo with `yarn install:all && yarn start:all:react`
3. Open up `localhost:8080` in your browser and use the login form in the header to login with an email
4. Using either commerce or events page, fill out any form and make an API request and ensure request went out with the user you logged in with
5. Then change your user and repeat step 4.
6. Ensure new request went out with your new email
=> Add Login Form to React Example App

react-example/cypress/fixtures/users/200.json, react-example/cypress/fixtures/users/400.json, react-example/cypress/integration/users/users.spec.ts
* [MOB-3930](https://iterable.atlassian.net/browse/MOB-3930)
Adds cypress suite for Users page in React example app
1. Run `yarn install:all && cd ./react-example && yarn cypress`
2. Run entire cypress suite in the pop-up window
3. Ensure all test pass
=> Add Users Cypress Suite for React Example App

.gitignore, README.md, example/src/index.ts, src/inapp/inapp.ts, src/inapp/index.ts, src/inapp/tests/inapp.test.ts
* [MOB-4296](https://iterable.atlassian.net/browse/MOB-4296)
Updates `getMessages` API to allow for deferring the display of in-app messages to any time the user wants. API looks like this:
```ts
const { request, triggerDisplayMessages } = getMessages(...options, { display: 'deferred' })
request().then(response => triggerDisplayMessages(response.data.inAppMessages))
```
1. Run a local JWT generation backend by [cloning this repo](https://github.com/Iterable/jwt-generator) and running `docker-compose up -d`
2. Run example app in this repo with `yarn install:all && yarn start:all`
3. Open up `localhost:8080` in your browser and login
* change you email in the codebase by replacing `iterable.tester@gmail.com` with your email
4. In `src/example/index.ts` change `getMessages` call to these …
=> Add More Display Options to getMessages 

src/inapp/utils.ts
* [MOB-4483](https://iterable.atlassian.net/browse/MOB-4483)
Adds `sandbox` property to iframe for in-app messages to prevent JS from executing
1. No real way to test this since there isn't a way for customers to get JS into their in-apps
* so just confirm the messages appear as normal
* Run a local JWT generation backend by [cloning this repo](https://github.com/Iterable/jwt-generator) and running `docker-compose up -d`
* Run example app in this repo with `yarn install:all && yarn start:all:react`
* Open up `localhost:8080` in your browser and login
=> Prevent JS From Running in In-App Messages IFrame

react-example/src/views/InApp.tsx, src/inapp/inapp.ts
* [MOB-3948](https://iterable.atlassian.net/browse/MOB-3948)
Adds a check to `resumeMessageStream` to first check to see if the in-app message presentation is paused.
Fixes issue where:
1. Customer code calls `getInAppMessages()` to display messages
2. Customer code then calls `resumeMessageStream` before first calling `pauseMessageStream`
3. Another in-app will appear on top of the previous one.
1. Run a local JWT generation backend by [cloning this repo](https://github.com/Iterable/jwt-generator) and running `docker-compose up -d`
2. Run example app in this repo with `yarn install:all && yarn start:all:react`
3. Open up `localhost:8080` in your browser and login with an email
4. Send yourself some in-app messages from Iterable app
5. Navigate to /inApp route and click "get messages …
=> Check for Pause before Invoking resumeMessageStream

README.md, src/inapp/inapp.ts, src/inapp/types.ts, src/inapp/utils.ts
* [MOB-4677](https://iterable.atlassian.net/browse/MOB-4677)
Adds an optional configuration property in getInAppMessages payload under the `closeButton` configuration.
```ts
closeButton?: {
...
isRequiredToDismissMessage?: boolean;
...
}
```
1. Set `requiredToDismissMessage: true` in getInAppMessages payload
2. Start up the react-example app
3. Login
4. Click InApp
5. Fetch in-app messages
6. Click outside the message -> Expected behavior: Message does NOT close
7. Click on close button -> Expected behavior: Message closes
=> [MOB-4677] Prevent dismissing of in-app message when clicking outside of message

src/inapp/inapp.ts, src/inapp/tests/inapp.test.ts, src/inapp/types.ts, src/inapp/utils.ts
(https://iterable.atlassian.net/browse/MOB-4576)
- Updates `getInAppMessages` path when `showInAppMessagesAutomatically` is not passed in and wraps the inapp message HTML in the API response with an iframe to be securely rendered to prevent JS execution
Run the example app and pull messages without showing messages automatically and see that the HTML returned is instead an iframe with the HTML content inside and a sandbox attribute
=> [MOB-4576] Secure unprotected raw html path with iframe

src/inapp/inapp.ts
* [MOB-4740](https://iterable.atlassian.net/browse/MOB-4740)
Messages that are delivered silently or read should not be displayed by the SDK. Filters out messages that have trigger.type set to 'never' so that these messages never get painted to the DOM.
1. Send yourself an in-app message proof with inbox off and deliver silently off
2. Start example app and paint messages
3. Expected: Message displays on screen
1. Send yourself an in-app message proof with inbox on and deliver silently off
2. Start example app and paint messages
3. Expected: Message displays on screen
1. Send yourself an in-app message proof with inbox on and deliver silently on
2. Start example app and paint messages
3. Expected: Message does NOT display on screen
1. Set up an in-app message with inbox on and deliver …
=> [MOB-4740] Filter out messages set to deliver silently

example/yarn.lock, react-example/yarn.lock
* [MOB-4800](https://iterable.atlassian.net/browse/MOB-4800)
Need to upgrade terser to latest version to resolve security vulnerability. Terser is used up the chain by `html-webpack-plugin#html-minifier-terser` so this upgrade bumps versions for these.
All unit tests pass.
=> [MOB-4800] Resolve dependency security vulnerability with terser

src/inapp/utils.ts
* [MOB-4840](https://iterable.atlassian.net/browse/MOB-4840)
The iframe document body has an 8px margin all around. The iframe height is set based on the body's scrollheight without taking the margin into consideration. Adds 16px to the iframe's scrollheight to eliminate the scrollbar that occurs when user uses the WYSIWYG editor to create their in-app.
1. Create WYSIWYG in-app template
2. Send to yourself
3. Render in web sample app
4. No scrollbar
=> [MOB-4840] Fix iframe height setting

package.json, src/inapp/inapp.ts, src/inapp/types.ts, yarn.lock
* [MOB-4920](https://iterable.atlassian.net/browse/MOB-4920)
Lays out the groundwork for consuming a new type of getMessages response ("message delta") and leveraging clientside storage.
Set up web SDK to call /inApp/getMessages.
Open up browser dev tools > Application tab.
Verify that inapp messages are now in the IndexedDB as a keval store.
Messages in cache should be stored as `[ messageId: string, message: InAppMessage ]`
See `src/inapp/types.ts` for InAppMessage type.
=> [MOB-4920] Implement message cache for web-sdk

README.md, react-example/src/views/InApp.tsx, src/inapp/inapp.ts, src/inapp/tests/inapp.test.ts, src/inapp/types.ts
* [MOB-4490](https://iterable.atlassian.net/browse/MOB-4490)
getInAppMessages has a second argument which can look like this:
```
getMessages(...options, true);
getMessages(...options, { display: string; })
```
We want to deprecate the usage of the first method. The second method is the newer, scalable option which allows customers to defer the display of the in-app messages to a time later in the future. The boolean value was the original implementation before this option was introduced.
The reason it still exists in the codebase is for backwards compatibility purposes.
All unit tests pass.
=> [MOB-4490] Deprecate boolean from getInAppMessages showInAppMessagesAutomatically param

jest.config.js, package.json, src/inapp/inapp.ts, src/inapp/types.ts, src/inapp/utils.ts, yarn.lock
* [MOB-4933](https://iterable.atlassian.net/browse/MOB-4933)
By default (as consistent with our other mobile SDKs), we persist messages in browser cache indefinitely until it reaches the expiration date. Automatically delete expired messages from the cache. Also, calculate remaining cache space and add new messages only if it fits in the cache.
Send yourself a message that will quickly expire.
Call getMessages.
Check that all messages appear in cache (assuming there's space).
After message expires, call getMessages again.
Observe that expired message gets removed from the cache.
=> [MOB-4933] Delete expired messages from cache & only add new messages if there is space in cache

src/inapp/utils.ts
* [MOB-4940](https://iterable.atlassian.net/browse/MOB-4940)
Add early return on determining cache quota size if the window doesn't even have indexedDB.
All unit tests pass.
Call getMessages and make sure you still get response.
=> [MOB-4940] Prevent caching if indexedDB is not present in browser window + refactoring

src/inapp/inapp.ts
* [MOB-4718](https://iterable.atlassian.net/browse/MOB-4718)
Safari blocks all bound event handlers (including our click event handlers) in iframes, so links will not work in Safari unless we circumvent the restriction by appending target to each link tag (only if it doesn't already have a target attribute).
TBD (test cases for permutations of Safari and Chrome and target and handleLinks)
=> [MOB-4718] Fix handleLinks support for iframe links in Safari

src/inapp/inapp.ts, src/inapp/types.ts
* [MOB-4959](https://iterable.atlassian.net/browse/MOB-4959)
Autogenerated close button doesn't work on Safari (desktop and mobile)
On Safari:
1. Create a web in-app message, including an auto-generated close button 
2. Send to self and visit the website on a mobile device and desktop
3. Web in-app message loads
4. No auto-generated close button appears
On Chrome/Firefox/Edge:
1. Using same message as above, send to self and visit website on a mobile device and desktop
3. Web in-app message loads
4. Clicking the auto-generated close button closes the message
=> [MOB-4959] Do not add autogenerated close button if in-app is displayed in Safari

react-example/src/views/InApp.tsx, src/inapp/utils.ts
* [MOB-4989](https://iterable.atlassian.net/browse/MOB-4989)
When customer does not use the showInAppMessagesAutomatically param, then the return value for the request promise’s content.html is an iframe (same as if the customer used the triggerDisplayMessages method). For the rendering purposes of the sample app, use the request() method to provide the response with InAppMessage in the content.html response.
Send html content message to self.
In sample app, click "Get messages (do not auto-display)".
Content.html value should be stringified html (for html content messages).
=> [MOB-4989] Render document string instead of iframe in sample app content html

src/constants.ts, src/inapp/inapp.ts, src/inapp/types.ts
* [MOB-4992](https://iterable.atlassian.net/browse/MOB-4992)
We are adding a new API endpoint for message delta (to be used in conjunction with the clientside message caching feature) in the near future. For an improved compatibility experience, we will provide support for an optional `useLocalCache` parameter at a later time, but for GA launch this parameter will not be available to be set. Customers may choose to use this parameter when it becomes available with a minor version update, but customers who do not want/need this feature will be able to do fine without it.
Send in-app messages to self.
Check that no `latestCachedMessageId` parameter exists on request.
No messages are added to the cache.
=> [MOB-4992] Support configuration option for using local cache

README.md
README updates: 
- Safari doesn't support `iterable://` and `action://` links.
- The SDK does not track `inAppDelete` events
=> README updates: Safari + custom links, inAppDelete events, closing message on Safari

README.md
N/A
There was a markdown error when attempting to render the `:rotating_light:` emoji due to missing some characters.
Grammer fix for a paragraph later in the `README.md` documentation.
N/A
=> docs: correcting spelling and markdown syntax

src/constants.ts, src/inapp/inapp.ts, src/inapp/index.ts, src/inapp/request.ts, src/inapp/tests/inapp.test.ts, src/inapp/tests/utils.test.ts, src/inapp/types.ts, src/inapp/utils.ts, src/index.ts
* [MOB-6229](https://iterable.atlassian.net/browse/MOB-6229)
Close button was being positioned relative to document rather than iframe boundaries.
For non-Safari browsers, return close x button to the iframe document.
For Safari browsers, keep close button on the main document and dynamically reposition relative to iframe boundaries.
In both Safari and non-Safari browsers:
1. Send in-app to self
2. Call getMessages in application
3. Expected: close x button appears over message iframe according to closeButton params
4. Expected: resizing window keeps close x button over message iframe
[MOB-6229]: https://iterable.atlassian.net/browse/MOB-6229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6229] Reposition close x button

README.md
Resolves https://github.com/Iterable/iterable-web-sdk/issues/210
* [MOB-6374](https://iterable.atlassian.net/browse/MOB-6374)
[MOB-6374]: https://iterable.atlassian.net/browse/MOB-6374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6374]: import docs discrepancy

README.md, src/inapp/tests/utils.test.ts, src/inapp/utils.ts
* [MOB-7175](https://iterable.atlassian.net/browse/MOB-7175)
Resolves https://github.com/Iterable/iterable-web-sdk/issues/237
There is a requested use case to have the `filterHiddenInAppMessages` method _not_ filter out JSON only messages. Because this method is used to paint messages to the i-frame and other users may depend on the current logic/behavior, we have opted to build a separate method with similar logic, albeit no longer filtering based on the presence of a message's html contents. 
[MOB-7175]: https://iterable.atlassian.net/browse/MOB-7175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7175]: add new filter method that leaves in JSON only messages

jest.config.js, package.json, src/authorization/authorization.ts, src/authorization/utils.ts, yarn.lock
Bump axios to resolve https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
Relied on unit tests to make sure it works.
=> Bump axios from 0.21.4 to 1.6.2

.babelrc, package.json, yarn.lock
We had issues when importing your library.
It seems it's a duplicated of https://github.com/Iterable/iterable-web-sdk/issues/228. Our current solution is to patch it to replace `??` with `||` but this seems a better solution if you are willing to merge it.
=> Fix nullish coalescing operator

example/src/index.ts, src/authorization/authorization.ts
For our own type safety, we needed access to some of you typings. Currently we patch the library by exporting them ourselves, but I think it's a safe QoL change
I tested it with the example project. 
For your own project:
- Install the package
- Import `GenerateJWTPayload`, `WithJWT`, `WithoutJWT` in the project
=> Export authorization typings

src/components/banner/index.tsx, src/components/card/index.tsx, src/components/notification/index.tsx
* [MOB-7850](https://iterable.atlassian.net/browse/MOB-7850)
> We have make UI responsible according to figma design
[MOB-7850]: https://iterable.atlassian.net/browse/MOB-7850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make UI responsive

src/embedded/embeddedManager.ts
* [MOB-8591](https://iterable.atlassian.net/browse/MOB-8591)
In `IterableEmbeddedManager`, `retrieveEmbeddedMessages` is incorrectly setting `placementIds` query parameter.
[MOB-8591]: https://iterable.atlassian.net/browse/MOB-8591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8591] Fix handling of placementIds when retrieving messages in IterableEmbeddedManager

react-example/src/components/EmbeddedForm.tsx, src/embedded/utils.ts, src/events/embedded/types.ts, src/events/events.test.ts
* [MOB-8646](https://iterable.atlassian.net/browse/MOB-8646)
`clickedUrl` isn't a part of the API req so changing it's name to more appropriately match the API. 
[MOB-8646]: https://iterable.atlassian.net/browse/MOB-8646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8646]: targetUrl not being sent on click

react-example/src/views/AUTTesting.tsx, src/anonymousUserTracking/criteriaCompletionChecker.test.ts, src/anonymousUserTracking/criteriaCompletionChecker.ts, src/constants.ts
=> Fixed single item matches code

src/embedded/embeddedManager.ts, src/request.ts
* [MOB-9087](https://iterable.atlassian.net/browse/MOB-9087)
1. In the EmbeddedMsgs view in the sample app, pass in additional params to `syncMessages` for the `placementIds` arg. 
2. When `getMessages` is called, make sure the params passed in are properly serialized for a URL. 
3. Test this for `api-inapp` as well. 
[MOB-9087]: https://iterable.atlassian.net/browse/MOB-9087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9087]: properly format query params for get requests

src/anonymousUserTracking/complexCriteria.test.ts, src/anonymousUserTracking/criteriaCompletionChecker.ts, src/anonymousUserTracking/tests/complexCriteria.test.ts, src/anonymousUserTracking/tests/criteriaCompletionChecker.test.ts
* [MOB-9055](https://iterable.atlassian.net/browse/MOB-9055)
[Web SDK] Criteria should not match but the anonymous user is converted incorrectly
See a JIRA ticket for the video
[MOB-9055]: https://iterable.atlassian.net/browse/MOB-9055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9055: Resolve nested criteria match issue

.eslintrc, src/embedded/embeddedPlacement.ts
* [MOB-9256](https://iterable.atlassian.net/browse/MOB-9256)
There have been a lot of for loops over basic arrays in PRs lately. We should instead be using array iterations or for-of. 
[MOB-9256]: https://iterable.atlassian.net/browse/MOB-9256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9256]: prefer for-of

README.md
* [DOCS-4818](https://iterable.atlassian.net/browse/DOCS-4818)
Removing the environment variable option for specifying that the SDK should point at Iterable's EUDC. Use the config option instead.
[DOCS-4818]: https://iterable.atlassian.net/browse/DOCS-4818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4818] EUDC instructions update

src/anonymousUserTracking/complexCriteria.test.ts, src/anonymousUserTracking/criteriaCompletionChecker.ts, src/anonymousUserTracking/tests/complexCriteria.test.ts
* [MOB-9222](https://iterable.atlassian.net/browse/MOB-9222)
> Criteria matching does not occur of multi nested criteria
> Please try following the steps outlined in the ticket.
[MOB-9222]: https://iterable.atlassian.net/browse/MOB-9222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Nested custom event check related change

src/anonymousUserTracking/complexCriteria.test.ts, src/anonymousUserTracking/criteriaCompletionChecker.ts, src/anonymousUserTracking/tests/anonymousUserEventManager.test.ts, src/anonymousUserTracking/tests/combinationLogicCriteria.test.ts, src/anonymousUserTracking/tests/compareArrayDataTypes.test.ts, src/anonymousUserTracking/tests/complexCriteria.test.ts, src/anonymousUserTracking/tests/constants.ts, src/anonymousUserTracking/tests/criteriaCompletionChecker.test.ts, src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/anonymousUserTracking/tests/validateCustomEventUserUpdateAPI.test.ts
* [MOB-9568](https://iterable.atlassian.net/browse/MOB-9568)
This pull request updates "criterias" to "criteriaSets"
[MOB-9568]: https://iterable.atlassian.net/browse/MOB-9568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9568] update "criterias" to "criteriaSets"

src/anonymousUserTracking/criteriaCompletionChecker.ts, src/anonymousUserTracking/tests/constants.ts, src/anonymousUserTracking/tests/nestedTesting.test.ts
* [MOB-9650](https://iterable.atlassian.net/browse/MOB-9650)
Add support to check for nested criteria a.b.c
[MOB-9650]: https://iterable.atlassian.net/browse/MOB-9650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9650 Added support for nested criteria match a.b.c

react-example/.eslintrc, react-example/src/index.tsx, react-example/src/indexWithoutJWT.tsx, react-example/src/styles/index.css, react-example/src/views/AUTTesting.tsx, src/anonymousUserTracking/anonymousUserEventManager.ts, src/anonymousUserTracking/tests/anonymousUserEventManager.test.ts, src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/anonymousUserTracking/tests/userUpdate.test.ts, src/anonymousUserTracking/tests/validateCustomEventUserUpdateAPI.test.ts, src/authorization/authorization.ts, src/constants.ts
* [MOB-9640](https://iterable.atlassian.net/browse/MOB-9640)
Keep AUT off until consent to track has been granted
[MOB-9640]: https://iterable.atlassian.net/browse/MOB-9640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9640] Keep AUT off until concent to track is granted

src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/authorization/authorization.test.ts, src/authorization/authorization.ts, src/commerce/commerce.ts, src/embedded/embeddedManager.ts, src/events/embedded/events.ts, src/events/events.ts, src/events/inapp/events.ts, src/inapp/request.ts, src/request.ts, src/users/users.ts, src/utils/commonFunctions.ts, src/utils/typeOfAuth.ts
* [MOB-9954](https://iterable.atlassian.net/browse/MOB-9954)
[MOB-9954]: https://iterable.atlassian.net/browse/MOB-9954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9954]: Fix Circular Dependency and Clean Up Auth Checks on API Calls

src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/authorization/authorization.test.ts, src/authorization/authorization.ts, src/commerce/commerce.test.ts, src/constants.ts, src/events/events.test.ts, src/request.ts, src/users/users.test.ts, src/utils/authorizationToken.ts
* [MOB-9703](https://iterable.atlassian.net/browse/MOB-9703)
Update SDK to support fetching a new JWT to use for the destinationUserId / destinationEmail when calling merge
[MOB-9703]: https://iterable.atlassian.net/browse/MOB-9703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9703] Added support for fetching new JWT prior to calling merge

react-example/src/index.tsx, react-example/src/indexWithoutJWT.tsx, src/authorization/authorization.ts, src/inapp/inapp.ts, src/request.ts
* [MOB-10086](https://iterable.atlassian.net/browse/MOB-10086)
[MOB-10086]: https://iterable.atlassian.net/browse/MOB-10086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10086]: Minor AUT Code Cleanup/Renaming

react-example/src/components/LoginFormWithoutJWT.tsx, react-example/src/index.tsx, react-example/src/indexWithoutJWT.tsx, src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/anonymousUserTracking/tests/userUpdate.test.ts, src/anonymousUserTracking/tests/validateCustomEventUserUpdateAPI.test.ts, src/authorization/authorization.ts, src/index.ts, src/request.ts, src/utils/commonFunctions.ts, src/utils/config.ts
* [MOB-10091](https://iterable.atlassian.net/browse/MOB-10091)
Renames config var, cleans up sample app without JWT fixes
[MOB-10091]: https://iterable.atlassian.net/browse/MOB-10091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10091]: AUT Pre-Bash Updates

src/anonymousUserTracking/tests/userMergeScenarios.test.ts, src/authorization/authorization.ts
* [MOB-10123](https://iterable.atlassian.net/browse/MOB-10123)
We should clear anon data on login even if `replayOnAnonToKnown` is set to false. `syncEvents` already handles the clearing of the data for us. 
[MOB-10123]: https://iterable.atlassian.net/browse/MOB-10123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10123]: Clear Anon Data When Replay is False

package.json, react-example/package.json, react-example/yarn.lock, yarn.lock
* [MOB-11441](https://iterable.atlassian.net/browse/MOB-11441)
* Bumps axios dependency version to 1.9.0, with package.json set to ^1.8.2 (earliest fixed version)
[MOB-11441]: https://iterable.atlassian.net/browse/MOB-11441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11441] Bump axios dependency version
